# Generated by Django 6.0.5 on 2026-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Autor de la Definición')),
                ('definition', models.TextField(verbose_name='Definición')),
                ('image_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ruta de la Imagen Estática')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Definición de IA',
                'verbose_name_plural': 'Definiciones de IA',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Concepto')),
                ('description', models.TextField(verbose_name='Descripción del Concepto')),
                ('image_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ruta de la Imagen Estática')),
            ],
            options={
                'verbose_name': 'Concepto General',
                'verbose_name_plural': 'Conceptos Generales',
            },
        ),
        migrations.CreateModel(
            name='Curiosity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Curiosidad')),
                ('text', models.TextField(verbose_name='Contenido de la Curiosidad')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Curiosidad',
                'verbose_name_plural': 'Curiosidades',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NeuralNetworkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Red Neuronal')),
                ('description', models.TextField(verbose_name='Qué es')),
                ('how_it_works', models.TextField(verbose_name='Cómo funciona')),
                ('image_path', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ruta de la Imagen Estática')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Tipo de Red Neuronal',
                'verbose_name_plural': 'Tipos de Redes Neuronales',
                'ordering': ['order', 'id'],
            },
        ),
    ]
