# Generated by Django 6.0.5 on 2026-05-20 12:30

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    # Obtener los modelos
    Curiosity = apps.get_model('education', 'Curiosity')
    AIDefinition = apps.get_model('education', 'AIDefinition')
    Concept = apps.get_model('education', 'Concept')
    NeuralNetworkType = apps.get_model('education', 'NeuralNetworkType')

    # 1. Poblar Curiosidades
    Curiosity.objects.bulk_create([
        Curiosity(
            title="El origen del término",
            text="En 1956, John McCarthy acuñó el término 'Inteligencia Artificial' durante la histórica Conferencia de Dartmouth, donde se fundó formalmente la disciplina como un campo de investigación independiente.",
            order=1
        ),
        Curiosity(
            title="El Test de Turing",
            text="Propuesto por Alan Turing en 1950, este test evalúa si una máquina puede exhibir un comportamiento inteligente que sea indistinguible del de un ser humano en una conversación textual.",
            order=2
        ),
        Curiosity(
            title="Procesamiento vs. Comprensión verdadera",
            text="Aunque un modelo como GPT puede redactar poesía compleja en segundos, no 'comprende' el significado ni siente las emociones de lo que escribe; simplemente predice matemáticamente la secuencia de palabras más probable basada en patrones estadísticos.",
            order=3
        ),
        Curiosity(
            title="La paradoja de Moravec",
            text="En IA, las tareas que son difíciles para los humanos (como jugar al ajedrez a nivel de gran maestro o resolver cálculo matemático avanzado) son sumamente fáciles para las computadoras; mientras que las tareas fáciles para los humanos (como caminar sobre terreno irregular o reconocer rostros en una multitud) son extremadamente complejas para una IA.",
            order=4
        ),
    ])

    # 2. Poblar Definiciones de IA
    AIDefinition.objects.bulk_create([
        AIDefinition(
            author="IEEE (Asociación de Ingenieros Eléctricos y Electrónicos)",
            definition="Sistemas que muestran comportamientos asociados con la inteligencia humana, como aprender, razonar, resolver problemas, comprender el lenguaje y percibir el entorno.",
            image_path=None,
            order=1
        ),
        AIDefinition(
            author="John McCarthy (Acuñador del término IA)",
            definition="Es la ciencia e ingeniería de hacer máquinas inteligentes, especialmente programas de cómputo inteligentes. Está relacionada con la tarea similar de usar computadoras para entender la inteligencia humana, pero la IA no tiene que limitarse a métodos que sean biológicamente observables.",
            image_path=None,
            order=2
        ),
        AIDefinition(
            author="Stuart Russell y Peter Norvig (Autores del texto estándar de IA)",
            definition="La Inteligencia Artificial es el estudio y diseño de agentes que reciben percepciones del entorno y realizan acciones sobre él de manera racional. El éxito de un agente se evalúa por el logro óptimo de sus objetivos definidos en base a su información y capacidad.",
            image_path=None,
            order=3
        ),
    ])

    # 3. Poblar Concepto Principal: Redes Neuronales Artificiales
    Concept.objects.create(
        name="Redes Neuronales Artificiales (RNA)",
        description="Son modelos matemáticos y computacionales inspirados de forma abstracta en la estructura biológica de los cerebros de los seres vivos. Consisten en un conjunto de nodos interconectados (llamados neuronas artificiales) organizados en capas secuenciales (entrada, ocultas y salida). Estas redes son capaces de aprender y generalizar patrones complejos a partir de la experiencia directa (datos), mediante el ajuste dinámico y progresivo del valor de sus conexiones o 'pesos sinápticos' a través de algoritmos de optimización matemática.",
        image_path="images/neural_network_main.png"
    )

    # 4. Poblar los 7 tipos de Redes Neuronales Artificiales
    NeuralNetworkType.objects.bulk_create([
        NeuralNetworkType(
            name="1. Red Monocapa (Perceptrón Simple)",
            description="Es la estructura más básica e histórica de una red neuronal artificial, compuesta por una única capa de nodos de entrada conectada directamente a un nodo de salida.",
            how_it_works="Toma múltiples entradas numéricas, calcula su suma ponderada multiplicándolas por sus respectivos pesos, añade un sesgo ('bias') y le aplica una función de activación de umbral simple para generar un resultado binario (0 o 1). Se limita a clasificar datos que son linealmente separables (que pueden dividirse con una línea recta).",
            image_path=None,
            order=1
        ),
        NeuralNetworkType(
            name="2. Red Multicapa (Perceptrón Multicapa - MLP)",
            description="Una evolución del perceptrón que incluye una o más capas intermedias (denominadas capas ocultas), lo que le permite resolver problemas complejos que no son linealmente separables (como la compuerta lógica XOR).",
            how_it_works="La información fluye hacia adelante desde la capa de entrada hasta la salida (feedforward). Durante la fase de entrenamiento, se calcula el error del resultado y se propaga hacia atrás capa por capa (backpropagation) utilizando cálculo diferencial para ajustar gradualmente los pesos y sesgos mediante el gradiente descendente.",
            image_path=None,
            order=2
        ),
        NeuralNetworkType(
            name="3. Redes Neuronales Convolucionales (CNN)",
            description="Son redes neuronales profundas diseñadas específicamente para procesar datos organizados en cuadrículas, siendo el estándar absoluto para el procesamiento de imágenes, visión artificial y reconocimiento de patrones visuales.",
            how_it_works="Aplican filtros matemáticos que recorren la imagen (convolución) para detectar características como bordes, esquinas y texturas en las primeras capas, y formas complejas en las capas profundas. Utilizan capas de agrupación (pooling) para reducir el tamaño de los datos y conservar la información espacial más relevante antes de la clasificación final.",
            image_path=None,
            order=3
        ),
        NeuralNetworkType(
            name="4. Redes Neuronales Recurrentes (RNN)",
            description="Redes diseñadas para procesar información secuencial o temporal, donde el orden y contexto de los elementos anteriores influye directamente en el significado del elemento actual (por ejemplo, textos o series de tiempo).",
            how_it_works="Poseen conexiones de retroalimentación interna que forman bucles, lo que actúa como una 'memoria a corto plazo'. La salida del procesamiento de un elemento de la secuencia vuelve a ingresar a la red junto con el siguiente elemento, permitiendo retener y acumular contexto temporal a lo largo del tiempo.",
            image_path=None,
            order=4
        ),
        NeuralNetworkType(
            name="5. Redes de Memoria a Corto y Largo Plazo (LSTM)",
            description="Una variante avanzada y sumamente robusta de las RNN que fue creada específicamente para resolver el problema matemático del desvanecimiento del gradiente en secuencias de texto muy largas.",
            how_it_works="Introducen una estructura llamada 'celda de memoria' que está regulada por compuertas (de entrada, de olvido y de salida). Estas compuertas determinan matemáticamente qué información contextual se conserva, cuál se borra y cuál se transmite al siguiente paso, logrando recordar dependencias de largo alcance.",
            image_path=None,
            order=5
        ),
        NeuralNetworkType(
            name="6. Redes Autoencoders (Autocodificadores)",
            description="Son arquitecturas de aprendizaje no supervisado diseñadas para aprender representaciones eficientes de los datos de entrada, ampliamente utilizadas para la compresión, reducción de ruido y análisis de anomalías.",
            how_it_works="Están divididas en dos partes simétricas: el Codificador (Encoder), que comprime la entrada a una dimensión reducida (llamada espacio latente o cuello de botella), y el Decodificador (Decoder), que toma esa representación comprimida e intenta reconstruir la entrada original con la menor pérdida de información posible.",
            image_path=None,
            order=6
        ),
        NeuralNetworkType(
            name="7. Redes de Transformadores (Transformers)",
            description="La revolucionaria arquitectura moderna que eliminó la necesidad de la recurrencia secuencial y es la base tecnológica detrás de los grandes modelos de lenguaje (LLMs) como GPT, LLaMA y Claude.",
            how_it_works="Utilizan un mecanismo llamado 'Autoatención' (Self-Attention), el cual permite procesar secuencias enteras de datos en paralelo. En lugar de procesar palabra por palabra, la red calcula simultáneamente la relevancia y la relación semántica de cada palabra con todas las demás palabras de la oración, capturando contextos hipercomplejos de forma eficiente.",
            image_path=None,
            order=7
        ),
    ])

def reverse_initial_data(apps, schema_editor):
    Curiosity = apps.get_model('education', 'Curiosity')
    AIDefinition = apps.get_model('education', 'AIDefinition')
    Concept = apps.get_model('education', 'Concept')
    NeuralNetworkType = apps.get_model('education', 'NeuralNetworkType')

    Curiosity.objects.all().delete()
    AIDefinition.objects.all().delete()
    Concept.objects.all().delete()
    NeuralNetworkType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data, reverse_initial_data),
    ]
